Отрисуй меня полностью (часть 1)
htmlacademy-javascript/488893-keksobooking-25 pull request #5
Opened 2022-03-10 21:16 UTC by IoanKing

2022-03-11 10:51 UTC, KletskovG requested changes
Пару небольших моментов можно улучшить

2022-03-11 10:51 UTC, KletskovG commented on js/card.js
> +const cardTemplate = document.querySelector('#card')
Я думаю, что здесь можно намного проще сделать 

`const cardTemplate = document.querySelector('#card .popup')`
Или
`const cardTemplate = document.querySelector('#card > .popup')`

2022-03-11 10:51 UTC, KletskovG commented on js/card.js
> +  card.querySelector('.popup__avatar').src = `${author.avatar}`;
Кажется, что  в `author.avatar` уже будет хранится строка. Тогда тут можно просто `author.avatar указать`

2022-03-13 14:44 UTC, IoanKing commented on js/card.js
> +const cardTemplate = document.querySelector('#card')
Данные записи не срабатывают - возвращают null значения. Судя по описанию на MDN - контент template ... не отображается во время загрузки страницы...
Во время эксперимента с консолью выяснилось - что template содержит фрагмент, а не DOM элементы, из-за этого нельзя обращаться к его потомкам?
![2022-03-13_17-41-14](https://user-images.githubusercontent.com/41145341/158064904-f59949aa-9230-4df3-863a-a9f0a21e232f.jpg)

2022-03-13 14:47 UTC, IoanKing commented on js/card.js
> +  card.querySelector('.popup__avatar').src = `${author.avatar}`;
Поправил.

2022-03-13 14:50 UTC, IoanKing commented on js/card.js
> +  }
Меня смущает такая запись. Точно нужно скрывать с помощью vissually-hidden? Или можно просто удалять элементы из разметки?
Цитата условия ТЗ: _Предусмотрите ситуацию, когда данных для заполнения не хватает. Например, отсутствует описание. В этом случае соответствующий блок в карточке скрывается._

2022-03-13 14:56 UTC, IoanKing commented on js/card.js
> +  }
Меня также смущает данная конструкция. Не нужно выносить в отдельную функцию?
Просто если её делать отдельной функцией в нее нужно передавать и offer.features и card.
Мне кажется это неправильным.

2022-03-14 10:51 UTC, KletskovG commented on js/card.js
> +  }
Тут можно делать на твое усмотрение. Главное, чтобы в случае такой ошибки пользовательский опыт не страдал. Чаще всего стараются даже не добавлять элементы в DOM, если данных не хватает. То есть можно отдать предпочтение в сторону удаления элемента. Однако, и другие варианты тоже вполне себе подходят

2022-03-14 11:00 UTC, KletskovG commented on js/card.js
> +  }
Да, можно спокойно вынести в отдельную функцию, в этом нет ничего плохоо - наоброт, получится более удобно организовать код. Можешь это сделать в следующей домашке

2022-03-14 11:01 UTC, KletskovG approved these changes

2022-03-14 11:01 UTC, merged